# Generated by Django 6.0.1 on 2026-01-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchmakingticket",
            name="battle_id",
            field=models.ForeignKey(
                blank=True,
                max_length=36,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battle.battle",
            ),
        ),
    ]
