# Generated by Django 6.0.1 on 2026-01-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0002_matchmakingticket_battle_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchmakingticket",
            name="battle_id",
        ),
        migrations.AddField(
            model_name="matchmakingticket",
            name="battle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="battle.battle",
            ),
        ),
    ]
