# Generated by Django 6.0.1 on 2026-01-31 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0003_remove_matchmakingticket_battle_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="battle.problems",
            ),
        ),
    ]
