# Generated by Django 6.0.1 on 2026-01-31 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0004_battle_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="battle.problems"
            ),
        ),
    ]
