# Generated by Django 5.2.10 on 2026-02-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_alter_battle_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchmakingticket",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="problems",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="submissions",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
