# Generated by Django 5.2.10 on 2026-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0006_alter_matchmakingticket_id_alter_problems_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problems",
            old_name="statement",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="problems",
            name="test_input_path",
        ),
        migrations.RemoveField(
            model_name="problems",
            name="test_output_path",
        ),
        migrations.AddField(
            model_name="problems",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problems",
            name="input_format",
            field=models.TextField(default="No format provided"),
        ),
        migrations.AddField(
            model_name="problems",
            name="output_format",
            field=models.TextField(default="No format provided"),
        ),
        migrations.AddField(
            model_name="problems",
            name="samples",
            field=models.JSONField(default=list),
        ),
    ]
