# Generated by Django 5.2.10 on 2026-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0007_rename_statement_problems_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchmakingticket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="problems",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Submissions",
        ),
    ]
