# Generated by Django 5.2.10 on 2026-02-04 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("battle", "0008_alter_matchmakingticket_id_alter_problems_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=30)),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                            ("CE", "Compile Error"),
                            ("IE", "Internal Error"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("exec_time_ms", models.IntegerField(blank=True, null=True)),
                ("memory_kb", models.IntegerField(blank=True, null=True)),
                ("points", models.FloatField(blank=True, null=True)),
                ("compiler_output", models.TextField(blank=True, null=True)),
                ("stdout", models.TextField(blank=True, null=True)),
                ("stderr", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("judged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="battle.battle",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="battle.problems",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="Judge_submi_created_d74a38_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="Judge_submi_user_id_6960f7_idx",
                    ),
                    models.Index(
                        fields=["problem", "created_at"],
                        name="Judge_submi_problem_7fef7f_idx",
                    ),
                    models.Index(
                        fields=["verdict", "created_at"],
                        name="Judge_submi_verdict_b10d0e_idx",
                    ),
                ],
            },
        ),
    ]
